locales:
  myu:
    name: Munduruku Keyboards
    description: >-
      Mobile OS keyboards for the Munduruku language from the Divvun group
      at UiT.
  en:
    name: Munduruku Keyboards
    description: >-
      Mobile OS keyboards for the Munduruku language from the Divvun group
      at UiT.
  nb:
    name: Munduruku tastatur
    description: Mobiltastatur for Munduruku fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
